--- #YAML:1.0
name:                Document
version:             0.03-2
abstract:            Support for archival document files and directories.
license:             ~
author:              
    - Dale Amon
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Exporter:                      0
    Fault::Logger:                 0
    POSIX:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
